sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer lint
  - composer test
